refactor; new tests
- New template tests
  - Create template inputs & output models in
    tests/files/tem_in & tests/files/tem_out
- Refactor function order in tests and
  improve comments.
- Better document the local declarations.
- Rename variables for clarity and consistency
  with the style guide.
- Merge functions display-version() and
  display-usage() in new display-info().
- Simplify test::log-wrapper(), in test-log.
- Simplify ::generate-config-file().
- Make ::store-options-default() arguments
  be received by reference.
- Update .codeclimate.yml to disable SC2016.
- Add `CODING_STYLE.md` file.
- Minor updates, fixes and improvements.
- Version 0.1.69

diff --git a/tests/_test-blank b/tests/_test-blank
--- a/tests/_test-blank
+++ b/tests/_test-blank
@@ -1,38 +1,11 @@
 #!/usr/bin/env bash
 #
-# Use this as a model for a new test file, and replace every BLANK keyword.
+# Use this as a model for a new test file. Replace every BLANK placeholder word.
 
 
-#-------------------------------------------------------------------------------
-# ::init
-#
-# > $1 : when equals "run-all-tests", common test data cleanup wont happen here
-#
-test::init() {
-
-	# Change to the directory where this script is located
-	if [[ "${BASH_SOURCE%/*}" != "${BASH_SOURCE[0]}" ]]; then
-		cd -- "${BASH_SOURCE%/*}" || exit 1
-	fi
-
-	# shellcheck disable=SC1091
-	source ./helper &>/dev/null
-
-	# Run tests
-	test_setup
-	test::suite
-	test_teardown
-
-	test_summary "BLANK"
-
-	# Only do the final cleanup when the script is run independently
-	[[ $1 != RUN_ALL_TESTS ]] && test_final_cleanup
-
-} #::init()
-
-
-#-------------------------------------------------------------------------------
 # ::suite
+#
+#   Test the BLANK.
 #
 test::suite() {
 
@@ -59,11 +32,35 @@ test::suite() {
 	assert_failure "false"
 
 
-
-
-
-
 } #::suite()
+
+
+#-------------------------------------------------------------------------------
+# ::init
+#
+# > $1 : if equals "RUN_ALL_TESTS" then don't do final cleanup
+#
+test::init() {
+
+	# Change to the directory where this script is located
+	if [[ "${BASH_SOURCE%/*}" != "${BASH_SOURCE[0]}" ]]; then
+		cd -- "${BASH_SOURCE%/*}" || exit 1
+	fi
+
+	# shellcheck disable=SC1091
+	source ./helper &>/dev/null
+
+	# Run tests
+	test_setup
+	test::suite
+	test_teardown
+
+	test_summary "BLANK"
+
+	# Only do the final cleanup when the script is run independently
+	[[ $1 != RUN_ALL_TESTS ]] && test_final_cleanup
+
+} #::init()
 
 
 [[ "$0" == "${BASH_SOURCE[0]}" ]] && test::init "$@"
diff --git a/tests/test-arguments b/tests/test-arguments
--- a/tests/test-arguments
+++ b/tests/test-arguments
@@ -1,43 +1,14 @@
 #!/usr/bin/env bash
-#
-# Tests for the script arguments
-#
 
 
-#-------------------------------------------------------------------------------
-# ::init
-#
-# > $1 : when equals "run-all-tests", common test data cleanup wont happen here
-#
-test::init() {
-
-	# Change to the directory where this script is located
-	if [[ "${BASH_SOURCE%/*}" != "${BASH_SOURCE[0]}" ]]; then
-		cd -- "${BASH_SOURCE%/*}" || exit 1
-	fi
-
-	# shellcheck disable=SC1091
-	source ./helper
-
-	# Run tests
-	test_setup
-	test::suite
-	test_teardown
-
-	test_summary 'arguments'
-
-	# Only do the final cleanup when the script is run independently
-	[[ $1 != RUN_ALL_TESTS ]] && test_final_cleanup
-
-} #::init()
-
-
-#-------------------------------------------------------------------------------
 # ::suite
+#
+#   Tests for the script arguments.
 #
 test::suite() {
 
 	declare default newval newval2
+
 
 	test_h1 "Script Arguments"
 	# ========================
@@ -385,6 +356,34 @@ test::suite() {
 
 
 } #::suite()
+
+
+#-------------------------------------------------------------------------------
+# ::init
+#
+# > $1 : if equals "RUN_ALL_TESTS" then don't do final cleanup
+#
+test::init() {
+
+	# Change to the directory where this script is located
+	if [[ "${BASH_SOURCE%/*}" != "${BASH_SOURCE[0]}" ]]; then
+		cd -- "${BASH_SOURCE%/*}" || exit 1
+	fi
+
+	# shellcheck disable=SC1091
+	source ./helper
+
+	# Run tests
+	test_setup
+	test::suite
+	test_teardown
+
+	test_summary 'arguments'
+
+	# Only do the final cleanup when the script is run independently
+	[[ $1 != RUN_ALL_TESTS ]] && test_final_cleanup
+
+} #::init()
 
 
 [[ "$0" == "${BASH_SOURCE[0]}" ]] && test::init "$@"
diff --git a/tests/test-config b/tests/test-config
--- a/tests/test-config
+++ b/tests/test-config
@@ -1,39 +1,9 @@
 #!/usr/bin/env bash
-#
-# Tests for the configuration
-#
 
 
-#-------------------------------------------------------------------------------
-# ::init
-#
-# > $1 : when equals "run-all-tests", common test data cleanup wont happen here
-#
-test::init() {
-
-	# Change to the directory where this script is located
-	if [[ "${BASH_SOURCE%/*}" != "${BASH_SOURCE[0]}" ]]; then
-		cd -- "${BASH_SOURCE%/*}" || exit 1
-	fi
-
-	# shellcheck disable=SC1091
-	source ./helper &>/dev/null
-
-	# Run tests
-	test_setup
-	test::suite
-	test_teardown
-
-	test_summary 'config'
-
-	# Only do the final cleanup when the script is run independently
-	[[ $1 != RUN_ALL_TESTS ]] && test_final_cleanup
-
-} #::init()
-
-
-#-------------------------------------------------------------------------------
 # ::suite
+#
+#   Test the configuration.
 #
 test::suite() {
 
@@ -113,7 +83,7 @@ test::suite() {
 	assert "echo $newval"
 
 
-	# TODO test_h3 "Missing parameters"
+	# test_h3 "Missing parameters"
 	# ------------------------
 
 
@@ -240,6 +210,34 @@ config : DIR_TEMPLATES : t1"
 	assert "echo $newval" "b4"
 
 } #::suite()
+
+
+#-------------------------------------------------------------------------------
+# ::init
+#
+# > $1 : if equals "RUN_ALL_TESTS" then don't do final cleanup
+#
+test::init() {
+
+	# Change to the directory where this script is located
+	if [[ "${BASH_SOURCE%/*}" != "${BASH_SOURCE[0]}" ]]; then
+		cd -- "${BASH_SOURCE%/*}" || exit 1
+	fi
+
+	# shellcheck disable=SC1091
+	source ./helper &>/dev/null
+
+	# Run tests
+	test_setup
+	test::suite
+	test_teardown
+
+	test_summary 'config'
+
+	# Only do the final cleanup when the script is run independently
+	[[ $1 != RUN_ALL_TESTS ]] && test_final_cleanup
+
+} #::init()
 
 
 [[ "$0" == "${BASH_SOURCE[0]}" ]] && test::init "$@"
diff --git a/tests/test-helper b/tests/test-helper
--- a/tests/test-helper
+++ b/tests/test-helper
@@ -1,38 +1,6 @@
 #!/usr/bin/env bash
-#
-# Tests for the helper functions
-#
 
 
-#-------------------------------------------------------------------------------
-# ::init
-#
-# > $1 : when equals "run-all-tests", common test data cleanup wont happen here
-#
-test::init() {
-
-	# Change to the directory where this script is located
-	if [[ "${BASH_SOURCE%/*}" != "${BASH_SOURCE[0]}" ]]; then
-		cd -- "${BASH_SOURCE%/*}" || exit 1
-	fi
-
-	# shellcheck disable=SC1091
-	source ./helper &>/dev/null
-
-	# Run tests
-	#
-	# NOTE: calls to `test_setup` and `test_teardown` are included in the suite
-	test::suite
-
-	test_summary "helper"
-
-	# Only do the final cleanup when the script is run independently
-	[[ $1 != RUN_ALL_TESTS ]] && test_final_cleanup
-
-} #::init()
-
-
-#-------------------------------------------------------------------------------
 # ::suite
 #
 #   Test the test helper functions.
@@ -106,6 +74,34 @@ test::suite() {
 
 
 } #::suite()
+
+
+#-------------------------------------------------------------------------------
+# ::init
+#
+# > $1 : if equals "RUN_ALL_TESTS" then don't do final cleanup
+#
+test::init() {
+
+	# Change to the directory where this script is located
+	if [[ "${BASH_SOURCE%/*}" != "${BASH_SOURCE[0]}" ]]; then
+		cd -- "${BASH_SOURCE%/*}" || exit 1
+	fi
+
+	# shellcheck disable=SC1091
+	source ./helper &>/dev/null
+
+	# Run tests
+	#
+	# NOTE: calls to `test_setup` and `test_teardown` are included in the suite
+	test::suite
+
+	test_summary "helper"
+
+	# Only do the final cleanup when the script is run independently
+	[[ $1 != RUN_ALL_TESTS ]] && test_final_cleanup
+
+} #::init()
 
 
 [[ "$0" == "${BASH_SOURCE[0]}" ]] && test::init "$@"
diff --git a/tests/test-log b/tests/test-log
--- a/tests/test-log
+++ b/tests/test-log
@@ -1,43 +1,9 @@
 #!/usr/bin/env bash
-#
-# Tests for logging
-#
-# TODO:
-# - test prelog
-# - min max log level
-# - test missing arguments, and the set defaults
 
 
-#-------------------------------------------------------------------------------
-# ::init
-#
-# > $1 : when equals "run-all-tests", common test data cleanup wont happen here
-#
-test::init() {
-
-	# Change to the directory where this script is located
-	if [[ "${BASH_SOURCE%/*}" != "${BASH_SOURCE[0]}" ]]; then
-		cd -- "${BASH_SOURCE%/*}" || exit 1
-	fi
-
-	# shellcheck disable=SC1091
-	source ./helper &>/dev/null
-
-	# Run tests
-	test_setup
-	test::suite
-	test_teardown
-
-	test_summary 'log'
-
-	# Only do the final cleanup when the script is run independently
-	[[ $1 != RUN_ALL_TESTS ]] && test_final_cleanup
-
-} #test::init()
-
-
-#-------------------------------------------------------------------------------
 # ::suite
+#
+#   Tests for logging.
 #
 test::suite() {
 
@@ -91,7 +57,6 @@ test::suite() {
 
 
 
-
 	# test_h2 "other"
 	# ~~~~~~~~~~~~~~~~~~~~~~~~
 	# test_clean
@@ -117,7 +82,7 @@ test::suite() {
 #-------------------------------------------------------------------------------
 # ::log-wrapper
 #
-#   a wrapper for the log function
+#   A wrapper for the webera::log().
 #
 # > $1 : (bool) [envir] _PRELOG
 # > $2 : (int)  [envir] LOG_LEVEL
@@ -130,11 +95,37 @@ test::suite() {
 #
 # shellcheck disable=SC2034
 test::log-wrapper() {
-	(
-		_Log_presaved="$1"; Opt_log_level="$2"; Opt_log_file="$log_file"
-		webera::log "$3" "$4" "$5"
-	)
+	local Log_presaved="$1" Opt_log_level="$2" Opt_log_file="$log_file"
+	webera::log "$3" "$4" "$5"
 } #::log-wrapper()
+
+
+#-------------------------------------------------------------------------------
+# ::init
+#
+# > $1 : if equals "RUN_ALL_TESTS" then don't do final cleanup
+#
+test::init() {
+
+	# Change to the directory where this script is located
+	if [[ "${BASH_SOURCE%/*}" != "${BASH_SOURCE[0]}" ]]; then
+		cd -- "${BASH_SOURCE%/*}" || exit 1
+	fi
+
+	# shellcheck disable=SC1091
+	source ./helper &>/dev/null
+
+	# Run tests
+	test_setup
+	test::suite
+	test_teardown
+
+	test_summary 'log'
+
+	# Only do the final cleanup when the script is run independently
+	[[ $1 != RUN_ALL_TESTS ]] && test_final_cleanup
+
+} #test::init()
 
 
 [[ "$0" == "${BASH_SOURCE[0]}" ]] && test::init "$@"
