tests & config files, bugfix and improve
- Config Files & Settings:
  - Bugfix: private vars (starting with `_`) were being written in the config file.
  - Bugfix: private vars are no longer being read from the config file.
  - Bugfix: `FILE_CONFIG` was duplicated when generating a config file.
  - Bugfix: new config file couldn't be generated empty.
  - Remove warning about non existing global config files. Log existing files instead.
  - Improve previous setting value logging msg.
  - Minor comments improvements.
  - Minor log msg improvements.
- Tests:
  - Bugfix: failed tests didn't return exit code.
  - Bugfix: script could exit with error code wihout need.
  - Bugfix: multiple test error report lines needed a separator newline.
- Other:
  - Insert a newline at the closing brackets of most big functions.
- Version 0.1.43

diff --git a/tests/helper b/tests/helper
--- a/tests/helper
+++ b/tests/helper
@@ -95,6 +95,7 @@ helper_run_all_tests() {
 
 	test_final_summary
 
+	[[ "$TESTS_TOTAL_ERRORS" -gt 0 ]] && exit 1
 } # helper_run_all_tests()
 
 
@@ -182,11 +183,11 @@ test_summary() {
 	local testStr="$1"
 	local testReport="$(assert_end \'"$testStr"\' | tr -d '\n' )"
 
-	printf '\n  %s\n' "$(test_separator)"
+	printf '\n  %s' "$(test_separator)"
 
 	# No tests failed
 	if [[ "$(echo "$testReport" | cut -d' ' -f1)" == "all" ]]; then
-		printf '  %s\n' "$testReport"
+		printf '\n  %s\n' "$testReport"
 
 		# get the number of passed tests
 		local testNum="$(echo "$testReport" \
@@ -197,7 +198,9 @@ test_summary() {
 		local pattern='[0-9]\+ of [0-9]\+ .* tests failed.*$'
 		local whatFailed="$(printf "%s" "$testReport" | sed "s/\($pattern\)//" )"
 		local errorReport="$(printf "%s" "$testReport" | grep -o "$pattern" )"
-		printf '%s\n' "$whatFailed" | tr '\t' '\n' | sed 's/^/  /'
+
+		printf '%s\n' "$whatFailed" | tr '\t' '\n' \
+			| sed 's/\(test\ #[0-9]\)/\n> &/g' | sed 's/^/  /'
 		printf '  %s\n' "$(test_separator)"
 		printf '  %s\n' "$errorReport"
 
@@ -231,6 +234,8 @@ test_summary() {
 		local newTotalTime="$(awk "BEGIN {print $testTime+$previousTotalTime; exit}")"
 		echo "$newTotalTime" > "$TOTAL_TEST_TIME"
 	fi
+
+	[[ "$TESTS_TOTAL_ERRORS" -gt 0 ]] && exit 1
 } # test_summary()
 
 test_final_summary() {
@@ -266,7 +271,6 @@ test_final_cleanup() {
 # This function gets called on test error
 helper_cleanup_exit() {
 	test_teardown
-	[[ "$TESTS_TOTAL_ERRORS" -gt 0 ]] && exit 1
 }
 
 # This function gets called on abrupt exit
